apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-corp-erp-vite-nginx-app
  namespace: dummy-corp-erp-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-corp-erp-vite-nginx-app
  template:
    metadata:
      labels:
        app: dummy-corp-erp-vite-nginx-app
    spec:
      containers:
        - name: cfp-poseidon-admin-nginx
          image: localhost:32000/dummy-corp-erp-vite-app:latest
          ports:
            - name: http-port
              containerPort: 80
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 5Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
